- View/AggregatedStageDamage/AggregatedStageDamage.xaml
- View/AggregatedStageDamage/AggregatedStageDamage.xaml.cs
- View/AggregatedStageDamage/CalculatedStageDamageControl.xaml
- View/AggregatedStageDamage/CalculatedStageDamageControl.xaml.cs
- View/AggregatedStageDamage/ManualStageDamageControl.xaml
- View/AggregatedStageDamage/ManualStageDamageControl.xaml.cs
- View/App.xaml
- ViewModel/AggregatedStageDamage/AggregatedStageDamageEditorVM.cs
- ViewModel/AggregatedStageDamage/AggregatedStageDamageElement.cs
- ViewModel/AggregatedStageDamage/AggregatedStageDamageOwnerElement.cs
- ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- ViewModel/AggregatedStageDamage/ManualStageDamageVM.cs
- ViewModel/Saving/PersistenceManagers/StageDamagePersistenceManager.cs
- ViewModel/Study/FDACache.cs
- ViewModel/Utilities/ChildElement.cs
> Stage damage compute

- Importer/Rating/RatingFunction.cs
- View/AggregatedStageDamage/AggregatedStageDamage.xaml
- View/Inventory/StructureMissingElevationEditor.xaml
- View/StageTransforms/RatingCurveEditor.xaml
- View/Utilities/BoolToMissingConverter.cs
- View/Utilities/BoolToUnidentifiableConverter.cs
- ViewModel/AggregatedStageDamage/AggregatedStageDamageEditorVM.cs
- ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- ViewModel/AggregatedStageDamage/ManualStageDamageRowItem.cs
- ViewModel/AggregatedStageDamage/ManualStageDamageVM.cs
- ViewModel/Editors/BaseLoggingEditorVM.cs
- ViewModel/Editors/CurveEditorVM.cs
- ViewModel/Inventory/DefineSIAttributesVM.cs
- ViewModel/Inventory/OccupancyTypes/IOccupancyType.cs
- ViewModel/Inventory/OccupancyTypes/OccupancyType.cs
- ViewModel/Utilities/ImportFromFDA1Helper.cs
These are some task review fixes requested by Richard. This is for tasks 4 and 5.
> Task4 review updates

- View/AggregatedStageDamage/CalculatedStageDamageControl.xaml
- View/AggregatedStageDamage/CalculatedStageDamageControl.xaml.cs
- View/AggregatedStageDamage/InverseStageDischargeVisibilityConverter.cs
- View/AggregatedStageDamage/StageDischargeVisibilityConverter.cs
- View/Inventory/DefineSIAttributes.xaml
- ViewModel/AggregatedStageDamage/AggregatedStageDamageEditorVM.cs
- ViewModel/AggregatedStageDamage/AggregatedStageDamageElement.cs
- ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- ViewModel/AggregatedStageDamage/FrequencyElementWrapper.cs
- ViewModel/AggregatedStageDamage/ImpactAreaFrequencyFunctionRowItem.cs
- ViewModel/AggregatedStageDamage/StageDamageCurve.cs
- ViewModel/AggregatedStageDamage/StageDischargeElementWrapper.cs
- ViewModel/ImpactArea/ImpactAreaElement.cs
- ViewModel/Saving/PersistenceManagers/StageDamagePersistenceManager.cs
- ViewModel/Utilities/ImportFromFDA1Helper.cs
This PR completes the stage damage update described in this document:
https://www.hec.usace.army.mil/confluence/display/FDA/2022-07-11+Maintenance+Tasks+Discussion
> Stage damage update

- UserControls/UserControls.vbproj
- UserControls/packages.config
- View/FrequencyRelationships/CreateSyntheticFrequencyFunction.xaml
- View/FrequencyRelationships/CreateSyntheticFrequencyFunction.xaml.cs
- View/HEC.FDA.View.csproj
- View/ImpactArea/ImpactAreaImporter.xaml
- View/ImpactArea/ImpactAreaImporter.xaml.cs
- View/Inventory/ImportStructuresFromShapefile.xaml
- View/Inventory/ImportStructuresFromShapefile.xaml.cs
- View/Study/CreateNew.xaml
- View/Study/CreateNew.xaml.cs
- View/Study/ImportStudyFromFDA1.xaml
- View/Study/ImportStudyFromFDA1.xaml.cs
- View/Study/OpenExisting.xaml
- View/Study/OpenExisting.xaml.cs
- View/Utilities/ImportFromFDA1.xaml
- View/Utilities/ImportFromFDA1.xaml.cs
- View/WaterSurfaceElevation/WaterSurfaceElevationImporter.xaml
- View/WaterSurfaceElevation/WaterSurfaceElevationImporter.xaml.cs
- View/Watershed/TerrainBrowser.xaml
- View/Watershed/TerrainBrowser.xaml.cs
- ViewModel/FrequencyRelationships/CreateSyntheticFrequencyFunctionVM.cs
- ViewModel/HEC.FDA.ViewModel.csproj
- ViewModel/ImpactArea/ImpactAreaImporterVM.cs
- ViewModel/Inventory/ImportStructuresFromShapefileVM.cs
- ViewModel/WaterSurfaceElevation/WaterSurfaceElevationImporterVM.cs
- ViewModel/Watershed/TerrainBrowserVM.cs
The name of this branch is not named well. This has nothing to do with hydro hdf. This branch was swapping out the CA file and folder browser for the new ones.
> Hydraulic hdf

- View/AggregatedStageDamage/AggregatedStageDamage.xaml
- ViewModel/AggregatedStageDamage/CalculatedStageDamageRowItem.cs
- ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- ViewModel/AggregatedStageDamage/ManualStageDamageVM.cs
- ViewModel/AggregatedStageDamage/StageDamageConstructionType.cs
- ViewModel/AggregatedStageDamage/StageDamageCurve.cs
- ViewModel/Storage/Connection.cs
- ViewModel/Study/StudyElement.cs
- ViewModel/Utilities/ImportFromFDA1Helper.cs
track when a user has edited computed stage damage curves. Displays a label in the UI listing which curves have been edited.
> Tracking user modified computed stage damage curves

- View/Hydraulics/PathAndProbabilityTableControl.xaml
- View/ImpactAreaScenario/Editor/SpecificIASControl.xaml
- View/TableWithPlot/FdaDataGrid.cs
- ViewModel/AggregatedStageDamage/StageDamageCurve.cs
- ViewModel/FrequencyRelationships/AnalyticalFrequencyElement.cs
- ViewModel/Inventory/OccupancyTypes/OccTypeAsset.cs
- ViewModel/Utilities/CurveChildElement.cs
- ViewModel/Utilities/DefaultCurveData.cs
This PR has the backwards compatibility logic for table with plot.
> Round UI values

- ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- ViewModel/AggregatedStageDamage/StageDamageConfiguration.cs
- ViewModel/AggregatedStageDamage/StageDamageCurve.cs
- ViewModel/FrequencyRelationships/AnalyticalFrequencyElement.cs
- ViewModel/Hydraulics/GriddedData/HydraulicElement.cs
- ViewModel/Inventory/InventoryElement.cs
- ViewModel/Inventory/OccupancyTypes/OccTypeAsset.cs
- ViewModel/Inventory/OccupancyTypes/OccTypeItemWithRatio.cs
- ViewModel/Storage/Connection.cs
- ViewModel/TableWithPlot/CurveComponentVM.cs
- ViewModel/Utilities/CurveChildElement.cs
- ViewModel/Utilities/FileValidation.cs
config validation and other bug fixes and refactoring.
> Stagedamage configuration validation

- fda-model-test/unittests/StageDamageShould.cs
- fda-model-test/unittests/structures/ValueUncertaintyShould.cs
- fda-model/structures/ValueUncertainty.cs
The ComputeDamageWithUncertaintyOneCoordinateShouldComputeCorrecly test in StageDamageShould.cs has been fixed
> Stage damage should tests

- fda-model/stageDamage/ImpactAreaStageDamage.cs
> needed to validate impact area stage damage Fixes #777

- HEC.FDA.View/Alternatives/Results/AlternativeResults.xaml
- HEC.FDA.ViewModel/Alternatives/Results/AlternativeResultsVM.cs
> Remove AED from Alternative Results Report

- HEC.FDA.View/App.xaml
- HEC.FDA.View/Inventory/StructureMissingElevationEditor.xaml
- HEC.FDA.View/Utilities/SplashScreen.xaml
- HEC.FDA.View/Utilities/SplashScreen.xaml.cs
- HEC.FDA.View/ViewWindow.xaml.cs
- HEC.FDA.ViewModel/Inventory/ImportStructuresFromShapefileVM.cs
- HEC.FDA.ViewModel/Inventory/InventoryColumnSelectionsRowItem.cs
- HEC.FDA.ViewModel/Inventory/InventoryColumnSelectionsVM.cs
- HEC.FDA.ViewModel/Inventory/StructureMissingDataRowItem.cs
- HEC.FDA.ViewModel/Inventory/StructureMissingElevationEditorVM.cs
- HEC.FDA.ViewModel/Study/FdaStudyVM.cs
- HEC.FDA.ViewModel/Study/StudyPropertiesElement.cs
- HEC.FDA.ViewModel/Utilities/SplashScreenVM.cs
This is for issues #882, #881, #868
> Occtype missing values 882

- HEC.FDA.Importer/AggregatedDamage/AggregateDamageFunctionList.cs
- HEC.FDA.Importer/AsciiImportExport/AsciiImport.cs
- HEC.FDA.Importer/OccType/OccupancyType.cs
- HEC.FDA.Importer/OccType/OccupancyTypeList.cs
I hate all the crap in the test report that's just cw from the importer project. I'm troubleshooting some failures on github and it's been slowing me down. Just removing console writelines here.
> removing writelines that clutter the test log

- HEC.FDA.Model/compute/ImpactAreaScenarioSimulation.cs
- HEC.FDA.Model/paireddata/PairedData.cs
- HEC.FDA.Model/stageDamage/ImpactAreaStageDamage.cs
- HEC.FDA.Model/stageDamage/ScenarioStageDamage.cs
- HEC.FDA.ModelTest/integrationtests/TractableStageDamageTests.cs
- HEC.FDA.ModelTest/integrationtests/UncertainStageDamageTests.cs
- HEC.FDA.ModelTest/unittests/PairedDataShould.cs
- HEC.FDA.ModelTest/unittests/StageDamageShould.cs
- HEC.FDA.ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- HEC.FDA.ViewModel/AggregatedStageDamage/StageDamageConfiguration.cs
- HEC.FDA.ViewModel/Utilities/DefaultCurveData.cs
This is a small change. We've played with convergence criteria for some time, but we're at the place now where it should just match 1.4.3. I think we'll have the option to revisit later. 
Notice that convergence is different for EAD as it is for stage-damage. This is how 1.4.3 is wired. 
I worked on some tech debt along the way - better aligning responsibilities, though still not perfect.
> 357 update convergence criteria

- HEC.FDA.Model/metrics/SystemPerformanceResults.cs
- HEC.FDA.ModelTest/unittests/PerformanceTest.cs
> 946 calculate assurance for levee infinite loop

- HEC.FDA.View/ImpactAreaScenario/Editor/IASEditor.xaml
- HEC.FDA.View/ImpactAreaScenario/Editor/SpecificIASControl.xaml
- HEC.FDA.ViewModel/ImpactAreaScenario/Editor/IASEditorVM.cs
- HEC.FDA.ViewModel/ImpactAreaScenario/Editor/SpecificIASEditorVM.cs
- HEC.FDA.ViewModel/ImpactAreaScenario/IASElement.cs
- HEC.FDA.ViewModel/ImpactAreaScenario/SpecificIAS.cs
this should complete issue #963
> 956 UI updates

- HEC.FDA.ModelTest/integrationtests/BigInventoryStageDamageTest.cs
- HEC.FDA.ViewModel/Inventory/ImportStructuresFromShapefileVM.cs
- HEC.FDA.ViewModel/Inventory/StructureMissingDataRowItem.cs
- HEC.FDA.ViewModel/Inventory/StructureMissingElevationEditorVM.cs
- HEC.FDA.ViewModel/Inventory/StructuresMissingDataManager.cs
> SI Validation

- HEC.FDA.Model/compute/ImpactAreaScenarioSimulation.cs
- HEC.FDA.Model/stageDamage/ImpactAreaStageDamage.cs
- HEC.FDA.Model/structures/Inventory.cs
- HEC.FDA.ModelTest/unittests/PerformanceTest.cs
- HEC.FDA.ViewModel/AggregatedStageDamage/CalculatedStageDamageVM.cs
- HEC.FDA.ViewModel/ImpactAreaScenario/SpecificIAS.cs
- HEC.FDA.ViewModel/Storage/Connection.cs
> added stack trace to stage damage exception catch

- HEC.FDA.StatisticsTests/Histograms/HistogramTests.cs
- HEC.FDA.ViewModel/Hydraulics/GriddedData/GriddedImporterVM.cs
recreated with the help of github copilot
> recreate distributions with histograms

- HEC.FDA.Importer/AsciiImportExport/AsciiImport.cs
- HEC.FDA.Importer/ErrorDistribution.cs
> Fixes #1129

- HEC.FDA.Model/structures/ValueRatioWithUncertainty.cs
> fix validation of deterministic CSVRs

- HEC.FDA.ViewModel/Inventory/ImportStructuresFromShapefileVM.cs
- HEC.FDA.ViewModel/Inventory/InventoryColumnSelectionsVM.cs
Unintended consequence of updating from Database manager.
> fix bug preventing user from opening SI editor/importer

- HEC.FDA.Model/alternativeComparisonReport/AlternativeComparisonReport.cs
- HEC.FDA.ViewModel/AlternativeComparisonReport/Results/SpecificAltCompReportResultsVM.cs
- HEC.FDA.ViewModel/Alternatives/Results/DamageByDamCatVM.cs
- HEC.FDA.ViewModel/Alternatives/Results/DamageByImpactAreaVM.cs
- HEC.FDA.ViewModel/Alternatives/Results/DamageWithUncertaintyVM.cs
- HEC.FDA.ViewModel/Utilities/StringConstants.cs
I have finished out making changes to the strings displayed to the user for terminology about amortized damage.
> terminology changes in user interface

- HEC.FDA.View/FrequencyRelationships/FrequencyEditor/GraphicalControl.xaml
- HEC.FDA.ViewModel/FrequencyRelationships/FrequencyEditor/GraphicalVM.cs
this fix provides clarity in the intention of the confidence limits in the graphical frequency editor
> changed button label and added tool tip

- HEC.FDA.Model/stageDamage/ImpactAreaStageDamage.cs
Converted exceedance prob to non-exceedance
> Fixes #1191
